### ISSUE TITLE
break/continue are not parsed

### ISSUE THREAD

**Issue by nikomatsakis** [dada-lang/dada#127]
I just noticed that `break` and `continue` are not parsed. =) I think the validation/BIR code is mostly there. We should fix that!

### Expected syntax

```
break <expr>
continue
```

We should probably add some syntax for named loops but that seems like a separate, follow-on feature.

### Precedence

The precedence of `break` and `continue` should be *very* low, e.g., `break 22 + 44` should yield break with `66`, and `break foo().await` should do the expected thing.

**Comment by nikomatsakis** [comment]
A test:

```
class Pair(a, b)

async fn main() {
    x = loop {
        break Pair(22, 44)
    }

    print(x).await
}
```

**Comment by nikomatsakis** [comment]
Probably good to test `while` loops too

**Comment by noneback** [comment]
I'm quite interested in this issue, but I have no experience in PL area. May I give it a shot?

**Comment by XFFXFF** [comment]
Sure, it's yours now

**Comment by XFFXFF** [comment]
@noneback I assigned you but feel free to unassign yourself :)

**Comment by nikomatsakis** [comment]
@noneback would you like a few tips to help you get started?

**Comment by nikomatsakis** [comment]
The relevant code is

https://github.com/dada-lang/dada/blob/main/components/dada-parse/src/parser/code.rs

and here is an example of where the `return` keyword is parsed:

https://github.com/dada-lang/dada/blob/606c1d89146beee21ecdca542847fd346a65a3a4/components/dada-parse/src/parser/code.rs#L178-L188
