### ISSUE TITLE
Question: stop checking in (but keep generating) the ast/validated/bir files?

### ISSUE THREAD

**Issue by nikomatsakis** [dada-lang/dada#135]
I am wondering if we should remove the ast/validated/bir files from the test directory, or at least put them in `.gitignore`. I thought they'd be useful but they make git pull requests awfully hard to read.

(Similarly, I wonder if we should strip colors from the stdout...)

**Comment by brson** [comment]
I think removing colors would be an improvement.

I am not sure yet the value of having all the dumps in the test directory. The only advantage I see is that it _could_ help someone see if they _accidentally_ changed something they didn't expect, but it's so much noise that I doubt it's even useful for that. I know I never look at them.

There are times when you want to ensure some code definitely produces a specific intermediate / machine output, but doing it for every case might make the cases where it is important get lost in the noise.

I'd say remove them for now.

**Comment by XFFXFF** [comment]
I also think removing the color would be an improvement.   
The ast/validated/bir files are useful when I read the source code of the parser/validator/brew modules, they help me understand how these modules work. I don't look at them during code reviews or running `cargo dada test --bless`. I'd say put them in `.gitignore`

**Comment by nikomatsakis** [comment]
That all sounds good. I think I would happily remove the colors if I knew how to do it. =) I forget if that was hard for some reason.

**Comment by nikomatsakis** [comment]
I definitely find the IR files useful to have, but I agree with `.gitignore`.

**Comment by nikomatsakis** [comment]
Opened https://github.com/dada-lang/dada/issues/139
