### ISSUE TITLE
Modify test harness to stop emitting color; add IR reference files to gitignore

### ISSUE THREAD

**Issue by nikomatsakis** [dada-lang/dada#139]
Per https://github.com/dada-lang/dada/issues/135, we should modify the test harness...

* to stop emitting color in the stdout files
* to generate the various IR files but not to check if they have changed (they are for looking at, not for reference)

The second step allows us to add them to `gitignore` (and remove the existing files from the repository)

**Comment by nikomatsakis** [comment]
Actually, @lqd, in merging #140 I overlooked an issue!

That PR ignored *all* ref files, but I think we still want to be checking certain files-- actually, I guess it's just one.

Want to check:

* annotations in file match actual errors (:heavy_check_mark: this matches main)
* stdout/stderr from execution match `stdout.ref` and `stderr.ref` (and matches annotation in file) (:heavy_check_mark: this matches main, I believe)
* compiler output matches `ref.ref` file (:x: we don't check this on main now -- also, we should rename `ref.ref`)

Do not want to check (or commit into the repo), but do want to generate:

* IR generated (syntax.ref, validated.ref, bir.ref)
* LSP output (`lsp.ref`)

Maybe we should rename those files to `.debug` or something?

**Comment by lqd** [comment]
I'll take care of that

**Comment by nikomatsakis** [comment]
Oh, I forgot one thing -- `HeapGraph-*.ref` -- I'm torn on this one. I do want to be testing that the heap graph dump is successful and contains certain key elements, but the ref files contain an awful lot of details.

Still, I think for now we should keep them.

**Comment by nikomatsakis** [comment]
The idea is that they are testing that the `#?` output contains what we expect it to contain. Admittedly, I mostly ignore diffs that occur in them, which is a bad sign. :)

**Comment by nikomatsakis** [comment]
(One thing I was considering was trying to find some kind of "ascii-art" renderer for graphviz files and checking *that* in, I think I would read that much more happily...)

**Comment by nikomatsakis** [comment]
@lqd yes! The only tools I found for that were written in perl, which was kind of a drag.

**Comment by nikomatsakis** [comment]
Honestly, maybe we should do a web request to that site :)

**Comment by nikomatsakis** [comment]
(heh, or I guess setup our own...that'd be kind of rude)

**Comment by nikomatsakis** [comment]
I wonder if we could compile the whole kit-and-kaboodle to wasm somehow :)

**Comment by nikomatsakis** [comment]
@lqd filed https://github.com/dada-lang/dada/issues/150

**Comment by nikomatsakis** [comment]
@lqd oh my :) well, we could also host it? not sure how hard that would be. 

Still, it feels like overall it'd be better/easier to just add a way to dump the output in a more readable format than graphviz.

**Comment by nikomatsakis** [comment]
But I think i will mark this bug as fixed!

**Comment by lqd** [comment]
ASCII output would be super cool, but maybe svg or another image format would be easier and acceptable in the meantime ? It's not really easily readable as text, but neither is a sufficiently large/complicated .dot file. We can easily do svg output in pure rust via https://github.com/nadavrot/layout.
