### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by nikomatsakis** [dada-lang/dada#155]
I am working with a graphic designer to create a logo for Dada.

**Comment by nikomatsakis** [comment]
This is based on a famous piece of Dada artwork: https://www.moma.org/learn/moma_learning/marcel-duchamp-bicycle-wheel-new-york-1951-third-version-after-lost-original-of-1913/

**Comment by brson** [comment]
3 is best.

The bicycle theme is reminiscent of the rust logo for better or worse.

**Comment by guanqun** [comment]
Sorry to come out of nowhere, aside from 3, I think the second is quite nice too, as it has the "dada" in the picture, though the D has slightly bigger width.

**Comment by nikomatsakis** [comment]
> The bicycle theme is reminiscent of the rust logo for better or worse.

This was intended :)

**Comment by nikomatsakis** [comment]
Now available at https://github.com/dada-lang/dada-artwork
