### ISSUE TITLE
Untyped/gradual dada motivation

### ISSUE THREAD

**Issue by ammkrn** [dada-lang/dada#199]
Hi,
I think this is a really cool project. I'm curious about the choice of gradual typing and was very surprised to hear nikomatsakis say in #54 `I also really want a language that is completely usable without types`. The design docs just seem to list support for a dynamic/gradual fragment as a goal, but I would be really interested to know more about the motivation behind it. 

Thanks!

**Comment by nikomatsakis** [comment]
@ammkrn My motivation is that I think a certain segment of people learn best by being able to play with and execute programs. I think it'd be really helpful if you could teach dada concepts at first without introducing types, just showing dynamic errors of various kinds -- ideally you'd do the first few projects this way. Once people learn how that works, they can add in the type system and have an intuitive feeling for how the patterns it expresses are useful.

That said, I'm not sure if this will work out, it's an experiment. A second motivation is being able to hack together quick edits while debugging and the like.

**Comment by ammkrn** [comment]
Despite the super delayed reply, I really appreciate you sharing your thoughts. Thank you!
