### ISSUE TITLE
These are just a few questions

### ISSUE THREAD

**Issue by hack3rcon** [dada-lang/dada#234]
Hello,
I really want to know about this programming language but I didn't find much information:
1- This programming language was developed by Rust-Lang creator. What are the shortcomings of Rust-Lang?

2- In what fields is this programming language used?

Cheers.

**Comment by hack3rcon** [comment]
Hello,
Thank you so much for your reply.
Honestly, Rust-Lang is much more difficult than C/C++ programming languages and in my opinion, it cannot be a suitable programming language for beginners.
What fields is the Dada programming language designed for? For example, system or web programming or...
Most of this programming language is built with JavaScript programming language.

**Comment by brson** [comment]
The GitHub language stats are misleading when they indicate Dada is written in JavaScript: the Dada website/playground source is in this repo, which contains a lot of JavaScript.

The Dada compiler is written in Rust.

It's pretty early to know what fields dada is intended for, but I'm sure @nikomatsakis has ideas. It's primary their own thought experiment right now to solidify ideas about a next-generation Rust-style type system that is easier to understand and teach.

**Comment by hack3rcon** [comment]
Hi,
Thanks again.
I hope @nikomatsakis will answer my questions here.

**Comment by nikomatsakis** [comment]
I direct you to the FAQ (which is admittedly harder to find than I would like, should restructure the webpage):

https://dada-lang.org/docs/about/faq/

As for the shortcomings of Rust, well, I refer you to my blog =)

https://smallcultfollowing.com/babysteps/
