### ISSUE TITLE
Question: `fn =` syntax

### ISSUE THREAD

**Issue by nikomatsakis** [dada-lang/dada#54]
I do eventually expect to add types to Dada, but I also really want a language that is completely usable without types. I have begun to notice a certain kind of error creeping in even in the very few lines of dada code I've written thus far -- accidentally returning a value from a function. This arises because Dada has no semicolons. The pattern is something like this:

```
fn do_something(m) {
    m.insert("Dada", "needs a cuddly mascot")
}
```

Suppose that `insert` returns `bool` in Dada, as it does in Rust -- did you mean for `do_something` to return `bool`? That's kind of unclear, but I suspect very likely you did not.

### Proposal

My proposal is to change the function syntax so that it requires an `=` if you plan to return something. Therefore, the above code would always return unit, and the value of the final block would be thrown away. But you could write:

```
fn do_something(m) = {
    m.insert("Dada", "needs a cuddly mascot")
}
```

and then you would return bool.

### Observations

A. We could also permit `fn do_something() = m.insert("dada")`, which is cool. However, I eventually want `{ foo }` to be the syntax for a closure with no arguments, and that means that `= { .. }` is kind of a "special case" where the `{ }` do not mean closure. I think I'm ok with that, though, but I don't love it.

B. This feels consistent to me with being able to write `if foo { ... } else { ... }` for side-effects or `x = if foo { .... } else { ... }` to take the value. I think you can always tell from context whether the value is being used or not.

C. What worries me the most is that when we add types and where clauses, the formatting of the `=` becomes non-obvious. We've encountered this in Rust. Example:

```
fn do_something(
    arg: Arg,
): Foo 
where 
    Blah,
= {
    ...
}
```

I guess that's ok, but having a `=` at the start of a line just feels so alien to me. Maybe i'd get used to it. We could I suppose make the `=` optional if there is a type, since we can see what we want. I would however not like "untyped" and "typed" Dada to feel so different.

### Conclusion

Anyway, just wanted to jot this down. I realize there's a lot of context in my brain that I should start writing down, in terms of design goals and the like (`{...}` as a closure is an example, but so are

* avoid the confusion that arises about whether to put a semicolon on the last line
* reliability as a high priority for Dada, just like Rust, if not the *highest*
* return Rust's cool conflation of statements and expressions
* something else that I forgot now

**Comment by brson** [comment]
I think it's early and now is the time to experiment and this seems ok.

The main thing I like about this suggestion is that it requires typing an additional thing in order to get an additional capability, like with `let mut`.

The extra syntactic burden on typed dada is unfortunate, and I kinda wouldn't want to make `=` optional, for consistency and simplicity.

A slight alternative, or reformulation, would be to _not_ implicitly evaluate blocks to their tail expressions, but require blocks to use a special syntax in order to result in their tail expression. That syntax could be `= { ... }`. That would make your closure syntax not `{ ... }` but `= { ... }`. It would seem to be burdensome for every case of blocks that aren't a function body, though presumably most blocks that need to have a value are preceded by an `=` in some way, like `var foo = if ... { } else { }`.

Ok, another slight variation: if a block (or closure) appears in a tail position somewhere on the right-hand side of an assignment operation it has a tail value, if not it doesn't. Just an attempt to generalize a rule that requires putting `=` in the position you've suggested.

I wonder whether it's worth solving in untyped dada though, since type systems are a solution; whether there will be many more of these kinds of errors, with temptations to add non-type-based solutions.

**Comment by nikomatsakis** [comment]
I think we will have to see! 

Types are not a full solution: Rust's current rules are a common source of user confusion, or at least they used to be; I haven't heard that particular complaint in a while, maybe because error messages are better, or maybe because I'm not on the "front lines" of teaching people at that stage anymore. But it's true that using types I think we could make a simpler set of rules for Rust, as well.

The other big place I can imagine types making things more ergonomic has to do with permissions. As in Rust, I plan to have giving permissions be the default (I experimented with other defaults, but it didn't feel like it was working out well), but that means that when I write (e.g.) `foo(bar)`, I am giving ownership of `bar` away, so I might want to write `foo(bar.share)`. But if `foo` is declared with types and requests only shared permission:

```
fn foo(bar: shared String) { ... }
```

...then the `.share` could be inferred. Anyway, that's a separate topic all of its own.

**Comment by nikomatsakis** [comment]
I feel like the other option would be a lightweight way for blocks to express that they "pass up" their final value. This is akin to your idea of having `= {` be block syntax. Something like `^expr` as the final thing in the block. But I don't really like that either. =)

**Comment by nikomatsakis** [comment]
I guess one last idea while brainstorming -- 

Plausibly you could use a distinct set of braces. e.g. `{{` or `[` for a "block" that returns a value.  

Here are a whole bunch of variations based on what we've said... 

```
fn print_something() {
    22
}

fn compute_something() {{
    22
}}

fn compute_something() [
    22
]

fn compute_something() = {
    22
}

fn compute_something() return {
    22
}

fn compute_something() {
    =22
}

fn compute_something() {
    ^22
}
```

**Comment by nikomatsakis** [comment]
Thinking the `=22` option through more, it has implications that, while relatively clear, I'm not sure if I like, for example this:

```
fn compute_something() {
    if foo() {
        =22
    } else {
        =44
    }
}
```

It just feels a lot less *elegant* to me than deciding whether the final expression is a value based on the context-- but I can see that it would likely be easier to teach and *perhaps* clearer to read? That last part is not especially clear to me.

This is interesting because it's the kind of small-bore decision that is hard to make without experience and perhaps also observing some users.

**Comment by brson** [comment]
I've always liked the idea of `^` for situations that suggest pointing up the stack, and the

```
{
    ^foo
}
```

style examples do look kind of good to me. I agree though that having multiple branches all end in `^foo` is probably going to get ugly fast.

You could also prefix value-yielding blocks

```
fn foo() ^ {
    22
}
```

```
let foo = ^ {
    22
}
```

```
let foo = ^ if a {
    22
} else {
    22
}
```

But yeah it does seem unnecessary since in these cases its obvious the block needs to yield a value. Maybe this just does call for a special syntax just for function bodies.

**Comment by brson** [comment]
Here's one more idea, assuming that we just add a special syntax for the function block.

This approach has the downside you mentioned of requiring superflous syntax in typed dada:

```
fn do_something(
    arg: Arg,
): Foo 
where 
    Blah,
= {
    ...
}
```

But what if the extra syntax for value-yielding functions is the same syntax as for declaring return types?

```
fn a() -> {
    1
}

fn a() -> uint {
    1
}
```

**Comment by XFFXFF** [comment]
After reading the above discussion, it seems that no one has mentioned the use of return. Is there any disadvantage?
```
fn a() {
  return 1
}

fn a() -> uint {
  return 1
}
```

**Comment by nikomatsakis** [comment]
@XFFXFF Heh, yes, I am assuming we would not want to use `return`. I really like the Rust way of having the last value in a function be its return value. But it's good to include it on the list of options.

**Comment by nikomatsakis** [comment]
Hmm:

```
fn a() -> {
    1
}

fn a() -> uint {
    1
}
```

Is not bad, I admit. One downside is that, if we want to have the function return something that is not `{}`, we get in the position of deciding whether the next token is a type or not... but that seems survivable. We could even make the syntax for a closure with arguments be something like `x -> expr` which kind of "connects" to the `->` syntax (although I do have a soft spot for Rust's `|x| expr`).

**Comment by brson** [comment]
That same arrow syntax with where clauses but no types:

```
fn a() -> {
    1
}

fn a() -> uint {
    1
}

fn a() ->
    where T: Foo
{
    1
}
```

**Comment by nikomatsakis** [comment]
@XFFXFF I'm not sure if this is what you meant, but it occurs to me that we could do

```
fn a() return {
}
```

as a wordy alternative to `->`. 

```
fn a()
where
    T: Ord,
return {
}
```

I think overall I prefer `->`, I like also that it makes Dada feel a bit closer to Rust. =)

**Comment by XFFXFF** [comment]
@nikomatsakis  Yes, that's what I mean, and I prefer `->` too. =)

**Comment by nikomatsakis** [comment]
OK, I think this is settled, closing in favor of #103. We'll use `->` syntax and see how it feels.
