### ISSUE TITLE
dada files in test harness should have an annotation for errors at interpreter time

### ISSUE THREAD

**Issue by nikomatsakis** [dada-lang/dada#6]
See the test:

https://github.com/dada-lang/dada/blob/cff3102697ef4dee168db7e53da3a68960224a29/dada_tests/interpret/print_wrong_label.dada#L1-L3

It generates an error:

https://github.com/dada-lang/dada/blob/cff3102697ef4dee168db7e53da3a68960224a29/dada_tests/interpret/print_wrong_label.stdout#L1

But the dada file doesn't have any `#` comment indicating that error is expected. This seems inconsistent with the way we handle errors during parsing. I'd prefer if errors generated at runtime had to be commented (and no comment meant "runs successfully").

cc @brson -- this seems like one you might like

**Comment by brson** [comment]
I gave this a look but felt uncertain about how to implement it, mostly regarding whether the test harness should try to distinguish between diagnostics emitted at compile time and at run time.

**Comment by nikomatsakis** [comment]
I was expecting an annotation at the top of the file like

`#! PANIC foo bar baz`

which indicates that the result should be `Err` and the display message should match foo bar baz.

**Comment by brson** [comment]
I'll give it another look after https://github.com/dada-lang/dada/pull/85 lands.

**Comment by nikomatsakis** [comment]
> I was expecting an annotation at the top of the file like

I just realized that "at the top of the file" doesn't make sense: interpreter errors have spans like everything else, so the `#! PANIC` annotation should just go on a regular line. I am debating now whether to repurpose "PANIC" as a special sort of severity or to use a different sigil than `!`, e.g., `#@`. 

Anyway, it's a relatively minor point, the key thing is that there are static errors and runtime errors and we ought to be separating them *somehow*. I am imagining that at some point we'll probably have runtime warnings and other kinds of diagnostics too.

Maybe RUNTIME should be a "flag"?

```
#! ERROR
#! RUN ERROR
```

or maybe mandatory?

```
#! COMPILE ERROR|WARN|INFO
#! RUN ERROR|WARN|INFO
```

it looks a bit intense with the capital letters like that :)

anyway, enough bikeshedding, you get the idea.
