### ISSUE TITLE
strip whitespace when it uses tabs, too

### ISSUE THREAD

**Issue by nikomatsakis** [dada-lang/dada#61]
#57 removed leading whitespace (see #51), but it only handles spaces, not tabs. See this comment:

This is probably good enough, but it only strips leading *spaces*.

I feel like 

```
\t\tFoo
\t\tBar
```

should also work. To make it work, we would want to do

```rust
take_while(|c| c.is_whitespace())
```

and then collect into a *String*, I think. Not as simple, though.

_Originally posted by @nikomatsakis in https://github.com/dada-lang/dada/pull/57#discussion_r785300730_

**Comment by nikomatsakis** [comment]
cc @XFFXFF I assigned you but feel free to unassign yourself :)

**Comment by XFFXFF** [comment]
No problem, I might try to fix it tomorrow :)
