### ISSUE TITLE
Add integer suffixes to the parser

### ISSUE THREAD

**Issue by brson** [dada-lang/dada#62]
Right now there is compiler support for signed int types, but no way to create them. Per https://github.com/dada-lang/dada/pull/56#issuecomment-1013675589, add Rust-style integer suffixes to the parser so it can produce signed int types.

@nikomatsakis what suffixes do you want for these? "uint" / "int", "u64", "i64"?

**Comment by nikomatsakis** [comment]
Hmm, regarding suffixes, I don't know! Let's run with `i` and `u` for now?
