### ISSUE TITLE
Add binop test cases for signed ints

### ISSUE THREAD

**Issue by brson** [dada-lang/dada#63]
Basic binop execution was implemented in https://github.com/dada-lang/dada/pull/56, but without parser support for signed ints, so no test cases for signed ints.

After completing https://github.com/dada-lang/dada/issues/62, mirror the uint test cases in dada_tests/interpreter/ops for signed integers, also adding an extra test case for signed division overflow.

**Comment by XFFXFF** [comment]
fixed in https://github.com/dada-lang/dada/pull/129
