### ISSUE TITLE
Support escapes in our strings.

### ISSUE THREAD

**Issue by XFFXFF** [dada-lang/dada#66]
Our strings do not support escapes like `\t`, `\n`.
`print("Foo \nBar")` now gives 
```
Foo \nBar
```
it should give
```
Foo
Bar
```

**Comment by XFFXFF** [comment]
This might be more complicated than I thougnt, I used to think that escapes only consisted of '\t', '\r', '\n', etc., but when I read the rust reference, I realized that there are many more escapes than I thougnt.  :joy:
https://doc.rust-lang.org/reference/tokens.html#ascii-escapes  
![image](https://user-images.githubusercontent.com/30254428/149651222-ca5a2ec3-5dbb-4c24-ac0b-64b41e6c498b.png)
Should we support all of this? @nikomatsakis

**Comment by nikomatsakis** [comment]
@XFFXFF I think we don't have to support everything. Just `\n`, `\\`, and `\"` to start.
