### ISSUE TITLE
Tests for `+=` and friends

### ISSUE THREAD

**Issue by nikomatsakis** [dada-lang/dada#69]
@brson added binop support in #56 but I don't *think* it included tests for `+=`. We should add a test like

```
async fn main() {
    var x = 22
    x += 44
    if x == 66 {
        print("Huzzah").await
    } else {
        print("Uh-oh").await
    }
}
```

**Comment by XFFXFF** [comment]
`+=` and friends don't seem to work, our parser doesn't support parsing them currently.
