### ISSUE TITLE
`==` and friends don't seem to work for me

### ISSUE THREAD

**Issue by nikomatsakis** [dada-lang/dada#73]
Playing with the playground these tests weren't parsing correctly...

```
async fn main() {
    var x = 22 + 44
    
    if x == 66 {
        print("Huzzah").await
    }
}
```

similarly `>=` 66 and so forth. Not sure why. Probably something wrong with the `eat_op` function of the parser, perhaps I failed to order the "longer" binops first in the list?

**Comment by nikomatsakis** [comment]
cc @brson

**Comment by XFFXFF** [comment]
The reason for this bug is that our parser tries to parse `x` in `if x == 66` as a local variable
https://github.com/dada-lang/dada/blob/2dcdb615de8fd1919a3f8411f300666db45c5adb/components/dada-parse/src/parser/code.rs#L337-L355

**Comment by XFFXFF** [comment]
A simple solution is to try `eat_op(Op::EqualEqual)` before `eat_op(Op::Equal)` in the function post above, if successful, return `None`. What do you think? @nikomatsakis

**Comment by nikomatsakis** [comment]
Hmm. Interesting. I think this is a bug in `eat_op`. It was not *supposed* to accept an operator that is followed by other operators except in particular cases:

https://github.com/dada-lang/dada/blob/2dcdb615de8fd1919a3f8411f300666db45c5adb/components/dada-parse/src/parser.rs#L98-L105

I think that code needs to be something like this:

```rust
        // For some operators, it doesn't matter if they are adjacent
        // to other operators.
        if Op::ACCEPT_ADJACENT.contains(&op) {
            return Some((span, tokens));
        }

        // only return Some if this is the complete operator
        // (i.e., the operator `=` cannot match against a prefix of the input `==`)
        if let Some(Token::Op(_)) = tokens.() {
            return None;
        }

        // ...if not, we've got a match!
        Some((span, tokens))
```
