### ISSUE TITLE
operators are not implemented

### ISSUE THREAD

**Issue by nikomatsakis** [dada-lang/dada#8]
We parse operators but they're not really implemented correctly. How I expect them to work:

* [ ] move `dada_ir::op` into `dada_ir::code::syntax::op`
* [ ] introduce `dada_ir::code::validated::op` which contains *only* the "unary/binary operators" that we want in the end -- i.e., `+=` is not a validated op, but `+` is. That sort of thing.
* [ ] make `dada_ir::code::bir` take a `validated::op::Op`; maybe make it not hardcoded to binary operators, now that I think about it?
* [ ] in the interpreter, execute lhs to a value, then rhs, then apply the op.

I'm *tempted* to remove ops and replace them with intrinsics, but it seems like it'd be nice to not have every operator end the basic block. This might argue in favor of extended basic blocks in BIR but I don't want to think that hard.

**Comment by brson** [comment]
@nikomatsakis I see you removed the help wanted label here. Are you going to do this yourself?

**Comment by nikomatsakis** [comment]
No, I don't know why I removed that really.

**Comment by brson** [comment]
I'm giving this a try.

**Comment by brson** [comment]
I have this implemented for obvious cases here: https://github.com/brson/dada/tree/ops

I am going to take another day to write negative test cases and think about a few more cases.

**Comment by brson** [comment]
At the moment there is no way to create signed integers, so that code cannot be tested.

**Comment by nikomatsakis** [comment]
@brson feel free to open a draft PR, that would make it easier to review.

**Comment by nikomatsakis** [comment]
I think I was trying to figure out the difference between "help wanted" and "good first issue".

**Comment by nikomatsakis** [comment]
And decided "help wanted" would be like "Distinct skill sets from ones that Niko possesses"
