### ISSUE TITLE
It seems odd that `Expr` appears twice in validated.ref

### ISSUE THREAD

**Issue by XFFXFF** [dada-lang/dada#91]
https://github.com/dada-lang/dada/blob/12dd605181cc4ff36b88ea03a4f19357ef7c0015/dada_tests/hello_world/validated.ref#L21-L23
Now `Expr` always appears twice in the validated.ref, which seems a little odd to me, would it be better to only appear once? @nikomatsakis

**Comment by nikomatsakis** [comment]
@XFFXFF They are different counters -- one is the 'validated' id, the other is the 'syntax' id. It would be better if that were clearer. Maybe better to use `{}` form so we can give them names.

**Comment by nikomatsakis** [comment]
Or change the names to `SExpr` and `VExpr` or something.

**Comment by XFFXFF** [comment]
@nikomatsakis  I see, one more question, why do we need to show expr id in validated.ref or syntax.ref ? Actually, I can't get much information from these ids, what can you get from them?

**Comment by nikomatsakis** [comment]
@XFFXFF other parts of the code sometimes references the id of an expression -- e.g. the breakpoint is set at a particular expression. Being able to cross-reference and see which part of the code that refers to is useful. That said, I agree that it's harder to read than it used to be.
